### ISSUE TITLE
More detail in shooting mechanism articles

### ISSUE THREAD

**Issue by realalexlam** [purduesigbots/BLRS-Wiki#19]
Currently, under the shooting mechanisms, there is a lack of information in regards to what the difference between the different launching mechanisms is, in addition to how to create them. I believe that these changes should be made in order to give readers a better understanding of the differences between each mechanism when deciding which one would be the best for their robot (Pros & Cons for each design).

**Comment by WillXuCodes** [comment]
List of Articles To Revamp:

- [x] Puncher
- [x] Catapult
- [x] Flywheel

**Comment by WillXuCodes** [comment]
Done a couple years ago.
