### ISSUE TITLE
Include a notebooking section to the wiki

### ISSUE THREAD

**Issue by realalexlam** [purduesigbots/BLRS-Wiki#20]
Currently, on the wiki, there is a hardware and mechanics section, however, if this were to be a general wiki (where any VEX team can visit the wiki and learn/have their problems solved), I believe that it is best to also include a notebook section to help inform teams/introduce teams as to how to create a basic notebook. 
Change being proposed: Add a notebook section to the wiki.

**Comment by WillXuCodes** [comment]
Done a couple months ago.
