### ISSUE TITLE
New Linear Puncher Text

### ISSUE THREAD

**Issue by MaxJohnson0312** [purduesigbots/BLRS-Wiki#25]
Linear punchers are used most commonly when needing to launch an object (normally a ball), a far distance. They were most commonly used in Turning Point (2018-19) and in Nothing But Net (2015-16) where teams needed to launch balls (relatively small) across the field. In the case of Turning Point, they were often used because they could be used in different points on the field with angle changes. They were also liked in Turning Point because they give the ball extra force forwards. 

Different Designs of Linear Punchers:
Cam Powered - Cam-powered linear punchers use a cam (think Fibonacci spiral) in order to add tension to the puncher that is then released and fires the puncher. In Vex, these are often made of Poly Carbonate or the Vex Cam piece. The benefits to this are that they can be much cleaner, more powerful, and have less strain on the motor as the mechanical advantage is continually increased. 
//I have these images too, they are in google drive because I am bad at GitHub
https://drive.google.com/file/d/165zw5zvfFINJ9U7VwkmIm3ut4gPPxMbl/view?usp=sharing
https://drive.google.com/file/d/1YWpY9IZBu3ZwdNo8RJhnNlc2BxXBz4SI/view?usp=sharing

Slip Gear Powered - Slip Gear Linear Punchers are by far the more common style. This is because of their relative simplicity and smaller form factor. They consist of a linear slide with a toothed track **I CANNOT THINK OF THE RIGHT WORD AND IT ISN'T ON THE VEX WEBSITE** which slides under a stationary motor and slip gear set. A slip gear is a gear that has several teeth shaved off of it. The design is actuated by the slip gear (and its remaining teeth) rotating and pushing the slide backward. As soon as the slip gear gets to the teeth that have been shaved off, the slide is released, firing the mechanism.
//I have these images too, they are in google drive because I am bad at GitHub
https://drive.google.com/file/d/1LwLv17KGRR1tzAvANC4kGNZGdQmJSOA3/view?usp=sharing
https://drive.google.com/file/d/1ztzKuVr0TV3KmDFwT70JjbvTGZflBZIv/view?usp=sharing
https://drive.google.com/file/d/1-cvS0PwT46c6CCyv9ODpVH15qQ4lynGY/view?usp=sharing

A couple of things to note about the design:
The shooting is powered by elastic tension. This is most commonly created with rubber bands, however, surgical tubing is also used as it has a more consistent elasticity throughout it's length. The key to the tension is to not have any choking points where it could snap, or kink and create an inconsistent pull. 

The one characteristic common in all implementations is the slide being pushed or pulled back with the motor being stationary. This can be done in many ways, however, the stationary motor reduces the torque needed for firing, and also increases the consistency of the design.

**Comment by WillXuCodes** [comment]
Hey Max,

Thanks for the submission! We will try to parse this into a document and give you credit. What team should this go under?

Thanks,
-The Purdue SIGBots Wiki Development Team

**Comment by MaxJohnson0312** [comment]
Hello,
Sorry for the excessively late response. I am on team 91A if that is what you mean 

Maxwell Johnson
12th grade, Downingtown STEM Academy 
***@***.***
610-719-7292

**Comment by WillXuCodes** [comment]
Approved, will be merging both the puncher text and the flywheel text in soon. We have seperate edits for these two so it'll be a while until both the puncher and flywheel articles are updated on the live site. Hope to work with ya in the future!

**Comment by MaxJohnson0312** [comment]
Sounds good! Is there a specific area that you are still looking for work on? I just finished school and don’t have plans for a while
Maxwell Johnson
12th grade, Downingtown STEM Academy 
***@***.***
610-719-7292
