### ISSUE TITLE
New Fly Wheel Text

### ISSUE THREAD

**Issue by MaxJohnson0312** [purduesigbots/BLRS-Wiki#26]
**This is from team 91A (I plan to be on BLRS in the fall though) 
Flywheel
	A flywheel is a mechanism that is designed to store rotational energy as efficiently as possible. This is done by spinning a wheel or disk at very high speeds with very little friction. In Vex, the main application is to throw balls long distances with fairly high accuracy.
	Flywheels are often chosen over Catapults and Linear Punchers for their ability to shoot long distances, and shoot multiple objects rapidly. They were most common in the game 2016-2016 Nothing But Net where teams had to collect balls and quickly shoot them into goals across the field. They were also fairly common in the game 2018-2019 Turning Point where teams had to shoot balls in order to toggle flags.

Single Flywheel
	A single flywheel is by far the most common flywheel used in Vex because of it’s consistency and accuracy. Single flywheels use a single wheel spinning at high rpms with a back plate (most commonly lexan or ABS). The back plate is formed around the wheel and tuned for the right amount of compression (varies based on object being fired) and cut to the desired launch angle of the object. The biggest benefits of single flywheels over double flywheels are their consistency, reduced use of motors, and distance because of greater backspin. 
	Single flywheels were the dominant design of Nothing But Net. Below is a picture of 1104M in the world finals with a single flywheel (3/6 finals teams in NBN were 1104 with essentially the same robot). 
https://photos.app.goo.gl/jRRp4awR6Edc1VPn6
	This flywheel spun at extremely high RPMs and had the majority of the wheel’s mass on the very outside of the wheel which increased it’s moment of inertia thus making it easier to fire several balls in succession. This was paired with a ratchet and pawl (Shown in a different thread) that allowed the wheel to coast with no motor power and maintain most of its speed. 
	Single flywheels were also common in Turning Point where the main goal was precision, and power. Robots like 169A chose flywheels because they are very consistent, and allowed for quick double shots (especially later in the season). 169A’s robot is shown below.
	https://photos.app.goo.gl/giGEjA5wG4QpVrmz9
	This robot used many mechanics similar to what 1104 did in NBN. The biggest innovation of this robot was the addition of an angle changing hood. This hood allowed for the robot to shoot 2 flags(of different heights) very quickly and very accurately. 
	Both above robots can be found in CAD designs at the link below:
https://drive.google.com/drive/folders/1ZnRL8jq9E2jQJKYvb96y2rm86BvNj6sA?usp=sharing

Double Flywheel
	A Double flywheel is similar to a single flywheel but instead of a backboard, has another rotating wheel. These wheels are often placed horizontally next to each other (but have also been done vertically). They are much more advanced and allow for more tuning, most commonly changing the speed of a wheel to adjust the projectile’s path. When vertical, the wheels can have different speeds that allow for more/less backspin to make the object fly different distances. Double flywheels are larger, heavier, but most importantly need more compression because of the reduced contact time with the ball. This means that they take longer to spin up and put more strain on the motor. 
	Below is VCAT Robotic’s early season 15” VexU robot. It is one of the better known double flywheels. They did however change the design soon after this to use a single flywheel.
https://photos.app.goo.gl/n2Gy8ZqCGsnat3PG6

**Comment by WillXuCodes** [comment]
Approved, will be merging both the puncher text and the flywheel text in soon. We have seperate edits for these two so it'll be a while until both the puncher and flywheel articles are updated on the live site. Hope to work with ya in the future!
