### ISSUE TITLE
Performance improvement: Homepage Image Sizing

### ISSUE THREAD

**Issue by baylessj** [purduesigbots/BLRS-Wiki#28]
The source size for the team image on the BLRS wiki homepage is 6000x4000 pixels, but the maximum size that it renders to is just 750x500. The image currently loads very slowly on my machine due to its size and could load faster if reuploaded as 750x500.

**Comment by WillXuCodes** [comment]
This was improved with a 830 by 557 image, although it's more than the maximum size it's still a huge improvement over the old image.
