### ISSUE TITLE
Correction for Outputs Eq 1)

### ISSUE THREAD

**Issue by perryH0123** [purduesigbots/BLRS-Wiki#44]
I have found a small error in the definition for the equation of the linear velocity command. It appears to be referencing Controls Engineering in FRC Eq 8.20, but there is a missing subscript for v<sub>d</sub>, instead with `d` being multiplied into an arbitrary velocity, `v`.

Although this is a small oversight, I noticed it when I was trying to derive the calculations myself, and I figured that it may confuse other robotics students who aren't familiar with all of the equations in the system.

![image](https://user-images.githubusercontent.com/83685361/201848216-62c9804b-ed84-4537-8caf-febdbd09d8ff.png)

![image](https://user-images.githubusercontent.com/83685361/201849287-bb39b897-1b0f-42f1-b9bd-182885be60b3.png)

**Comment by baylessj** [comment]
Hi, thank you for catching this! I have a change request opened in our team's Gitbook instance, this should be fixed shortly.
